# Generated by Django 3.1.7 on 2021-03-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='testimonials_vleresim',
            field=models.CharField(max_length=250),
        ),
    ]
